name: Maven Release

on:
  workflow_dispatch:
    inputs:
      release-body:
        description: 'Text describing the contents of the release.'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  release:
    uses: jonasrutishauser/parent/.github/workflows/common-release.yml@v37
    with:
      name: 'Error Prone Maven Plugin'
      java-version: '21'
      release-body: ${{ github.event.inputs.release-body }}
    secrets:
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
